#!/usr/bin/env python3
"""Generate anim_data.h from bender_bit folder with 1-bit animation frames."""

import os
import sys
import glob

INPUT_DIR = os.path.expanduser("~/Downloads/bender_bit")
OUTPUT_FILE = os.path.join(os.path.dirname(os.path.abspath(__file__)), "src", "anim_data.h")

ANIMS = [
    ("music",   33,  8),
    ("happy",   19,  8),
    ("wakeup",  17,  6),
    ("headbob", 11, 10),
    ("orbit",   11,  8),
]

def bytes_to_c_array(data):
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    return "\n".join(lines)

def main():
    with open(OUTPUT_FILE, "w") as f:
        f.write("// anim_data.h — autogenerated by generate_anim_data.py, DO NOT EDIT\n\n")
        f.write("#ifndef ANIM_DATA_H\n")
        f.write("#define ANIM_DATA_H\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write("#define MAX_ANIMS  8\n")
        f.write("#define MAX_NAME   16\n\n")

        frame_arrays = []

        for name, num_frames, fps in ANIMS:
            f.write(f"// === {name} ({num_frames} frames) ===\n")
            for i in range(num_frames):
                path = os.path.join(INPUT_DIR, name, f"f{i:02d}.1bit")
                if not os.path.exists(path):
                    print(f"ERROR: missing {path}", file=sys.stderr)
                    sys.exit(1)
                with open(path, "rb") as pf:
                    data = pf.read()
                if len(data) != 7200:
                    print(f"ERROR: {path} is {len(data)} bytes, expected 7200", file=sys.stderr)
                    sys.exit(1)
                varname = f"anim_{name}_f{i:02d}"
                f.write(f"static const uint8_t {varname}[7200] = {{\n")
                f.write(bytes_to_c_array(data))
                f.write("\n};\n\n")

            ptrs = ", ".join(f"anim_{name}_f{i:02d}" for i in range(num_frames))
            arr_name = f"{name}_frames"
            f.write(f"static const uint8_t *const {arr_name}[] = {{ {ptrs} }};\n\n")
            frame_arrays.append((name, num_frames, fps, arr_name))

        f.write("typedef struct {\n")
        f.write("    const char *name;\n")
        f.write("    int frames;\n")
        f.write("    int fps;\n")
        f.write("    uint32_t delay_ms;\n")
        f.write("    const uint8_t *const *frames_data;\n")
        f.write("} anim_t;\n\n")

        f.write(f"#define ANIM_COUNT {len(frame_arrays)}\n\n")
        f.write(f"static const anim_t anims[ANIM_COUNT] = {{\n")
        for name, num_frames, fps, arr_name in frame_arrays:
            delay_ms = 1000 // fps
            f.write(f'    {{"{name}", {num_frames}, {fps}, {delay_ms}, {arr_name}}},\n')
        f.write("};\n\n")
        f.write("#endif\n")

    print(f"Generated {OUTPUT_FILE}")
    total = sum(nf for _, nf, _ in ANIMS)
    print(f"  {len(ANIMS)} animations, {total} frames, {total * 7200} bytes")

if __name__ == "__main__":
    main()
